OnboardingV2Minimal/force-app/main/default/objects/Vendor_Program_Requirement_Group__c/Vendor_Program_Requirement_Group__c.object-meta.xml
<CustomObject>
    <description>This groups together multiple definitions and can be assigned to multiple vendor programs.</description>
    <label>Vendor Program Requirement Group</label>
    <nameField>
        <label>Vendor Program Requirement Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Program Requirement Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OnboardingV2Minimal/force-app/main/default/objects/Vendor_Program_Requirement_Group__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lifecycle_Status_Values</valueSetName>
    </valueSet>
</CustomField>

OnboardingV2Minimal/force-app/main/default/globalValueSets/Lifecycle_Status_Values.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Deprecated</fullName>
    </customValue>
    <description>Draft, Active, Deprecated, etc.</description>
    <masterLabel>Lifecycle Status Values</masterLabel>
</GlobalValueSet>

OnboardingV2Minimal/force-app/main/default/classes/test/TestVendorProgramRequirementGroupFactory.cls
@isTest
public class TestVendorProgramRequirementGroupFactory {

    public static Vendor_Program_Requirement_Group__c create(Boolean doInsert, String label) {
        Vendor_Program_Requirement_Group__c vendorProgramRequirementGroup = new Vendor_Program_Requirement_Group__c(
            Name = label,
            Status__c = 'Active',
            Active__c = true
        );
        TestDataFactoryUtil.maybeInsert(vendorProgramRequirementGroup, doInsert);
        return vendorProgramRequirementGroup;
    }

    public static Vendor_Program_Requirement_Group__c create(Boolean doInsert) {
        Vendor_Program_Requirement_Group__c vendorProgramRequirementGroup = new Vendor_Program_Requirement_Group__c(
            Name = 'Requirement Group ' + DateTime.now().getTime()
        );
        TestDataFactoryUtil.maybeInsert(vendorProgramRequirementGroup, doInsert);
        return vendorProgramRequirementGroup;
    }
}