OnboardingV2Minimal/force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OnboardingV2Minimal/force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Program Region</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Division__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ATT</fullName>
            </value>
            <value>
                <fullName>CATV</fullName>
            </value>
            <value>
                <fullName>CCT</fullName>
            </value>
            <value>
                <fullName>CEN</fullName>
                <color>#0B6FCE</color>
                <label>CEN</label>
            </value>
            <value>
                <fullName>COLR</fullName>
            </value>
            <value>
                <fullName>D2D</fullName>
            </value>
            <value>
                <fullName>DOMR-Domestic</fullName>
            </value>
            <value>
                <fullName>DTV/HSP/RSP</fullName>
            </value>
            <value>
                <fullName>ESR</fullName>
                <color>#E27001</color>
                <label>ESR</label>
            </value>
            <value>
                <fullName>House</fullName>
            </value>
            <value>
                <fullName>HSP</fullName>
            </value>
            <value>
                <fullName>Mass Merch</fullName>
            </value>
            <value>
                <fullName>MDUR</fullName>
            </value>
            <value>
                <fullName>NAT</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>WES</fullName>
                <color>#78C953</color>
                <label>WES</label>
            </value>
            <value>
                <fullName>PHS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingV2Minimal/force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Program Territory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ABW</fullName>
            </value>
            <value>
                <fullName>AFG</fullName>
            </value>
            <value>
                <fullName>AGO</fullName>
            </value>
            <value>
                <fullName>AIA</fullName>
            </value>
            <value>
                <fullName>AKW</fullName>
            </value>
            <value>
                <fullName>ALA</fullName>
            </value>
            <value>
                <fullName>ALB</fullName>
            </value>
            <value>
                <fullName>ALM</fullName>
            </value>
            <value>
                <fullName>AND</fullName>
            </value>
            <value>
                <fullName>ANT</fullName>
            </value>
            <value>
                <fullName>ARE</fullName>
            </value>
            <value>
                <fullName>ARG</fullName>
            </value>
            <value>
                <fullName>ARGDTVLATA</fullName>
            </value>
            <value>
                <fullName>ARM</fullName>
            </value>
            <value>
                <fullName>ASM</fullName>
            </value>
            <value>
                <fullName>ATG</fullName>
            </value>
            <value>
                <fullName>ATX</fullName>
            </value>
            <value>
                <fullName>AUS</fullName>
            </value>
            <value>
                <fullName>AUT</fullName>
            </value>
            <value>
                <fullName>AZE</fullName>
            </value>
            <value>
                <fullName>BDI</fullName>
            </value>
            <value>
                <fullName>BEL</fullName>
            </value>
            <value>
                <fullName>BEN</fullName>
            </value>
            <value>
                <fullName>BFA</fullName>
            </value>
            <value>
                <fullName>BGD</fullName>
            </value>
            <value>
                <fullName>BGR</fullName>
            </value>
            <value>
                <fullName>BHR</fullName>
            </value>
            <value>
                <fullName>BHS</fullName>
            </value>
            <value>
                <fullName>BIH</fullName>
            </value>
            <value>
                <fullName>BLM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

OnboardingV2Minimal/force-app/main/default/classes/repository/AccountRepository.cls
/**
 * Repository for Account data access operations
 * Handles all SOQL queries for Account records
 */
public with sharing class AccountRepository {
    
    /**
     * Gets accounts with basic fields for onboarding eligibility checks
     * @param limitCount Maximum number of records to return
     * @return List of Account records
     */
    public static List<Account> getAccountsForOnboarding(Integer limitCount) {
        Integer limitValue = limitCount != null && limitCount > 0 ? limitCount : 50;
        
        return [
            SELECT Id, Name, Territory__c, Region__c
            FROM Account
            ORDER BY Name
            LIMIT :limitValue
        ];
    }
}